Support aiomysql
RextTeam/MySQLer pull request #6
Opened 2022-04-23 13:52 UTC by tuna2134

2022-04-23 20:51 UTC, tasuren commented on mysqler/mysql.py
> +            await self.wait_event.wait()
これだとまった後に結局何も実行されないってなるけどいいの？

2022-04-24 00:40 UTC, tuna2134 commented on mysqler/mysql.py
> +            await self.wait_event.wait()
一旦クローズしないとな

2022-04-24 03:59 UTC, tasuren commented on mysqler/mysql.py
> +            await self.wait_event.wait()
what

2022-04-24 04:38 UTC, tuna2134 commented on mysqler/mysql.py
> +            await self.wait_event.wait()
> what

つまりawait self.close()されるまで待つって感じ

2022-04-24 04:40 UTC, tuna2134 commented on mysqler/mysql.py
> +            await self.wait_event.wait()
そしたら動くってやつ

2022-04-24 04:42 UTC, tuna2134 commented on mysqler/mysql.py
> +            await self.wait_event.wait()
そしたら動くってやつ

2022-04-24 05:17 UTC, tasuren commented on mysqler/mysql.py
> +            await self.wait_event.wait()
elseになってるから待った後実行されなくない？

2022-04-24 05:19 UTC, tuna2134 commented on mysqler/mysql.py
> +            await self.wait_event.wait()
あ
草

2022-04-24 05:21 UTC, tuna2134 commented on mysqler/mysql.py
> +            await self.wait_event.wait()
どう？

2022-04-24 05:24 UTC, tasuren approved these changes
よく見てないけどまあいいんちゃう

2022-04-24 05:24 UTC, tasuren requested changes
ドキュメンテーションつけないの？

2022-04-24 05:25 UTC, tuna2134 commented
> ドキュメンテーションつけないの？

君に任せるわ()

2022-04-24 05:26 UTC, tuna2134 commented
> よく見てないけどまあいいんちゃう

草

2022-04-24 05:27 UTC, merged